[package]
name = "mousefix"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.59", features = [ "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader" ]}
tray-icon = "0.9"

[features]
windowless = []
